### PR TITLE
Change the way to set alias and description

### PR DESCRIPTION
**Pull request by gabrielfedel**
A new proposal to set alias and description to AI channels.

This is already in use for tests on TIGER, but I haven't committed before to check if is ok.

### CODE REVIEW

**Review by ThomasFayESS — CHANGES_REQUESTED** [review]
Digitiser instance enumeration is undesireable in aliased names. In fact this was one of the main functions of the aliasing - to remove digitiser specific information from the PV names for RF data acquisition.
A one line comment to separate channels in the configuration files would be helpful I think. I.e. "Board 1, Channel 4 = Cavity Field." type commment.
Can we have a header line in the *.input file to name the two fields?

**Comment by gabrielfedel** [comment]
You are right. 

I didn't understand the suggested comment, is not to be parsed? is just for information ?

A header is a good idea too.

Do you think is necessary to indicate what board is being used on .input ? or can we left as an input argument to script (the same as now)

**Comment by ThomasFayESS** [comment]
Just to make transparent our discussion before, regarding the comment below:
"I didn't understand the suggested comment, is not to be parsed? is just for information ?"
Here, I can clarify that my comment "A one line comment to separate channels in the configuration files would be helpful I think. I.e. "Board 1, Channel 4 = Cavity Field." type commment." is referring specifically to the 'config-aliasing#.iocsh' snippet and is aimed at helping (human) IOC debuggers in understanding this startup snippet more easily.

**Comment by gabrielfedel** [comment]
Thank you!

Currently the script use the line order in input file to know what channel is to be "aliased", and the board is indicate by an argument to script. Can we keep like this? or is better we indicate the board on the input file too?

**Comment by ThomasFayESS** [comment]
My preference is to avoid implicit assumptions as a default position (exceptions may apply with good justification). Therefore I would propose that both the digitiser board enumeration and the channel number are specified explicitly in the input file.

**Comment by ThomasFayESS** [comment]
Actually, regarding the above comment, I don't have a preference for whether the digitiser board number is specified in script input or in the input file. My only requirement is that it is made explicitly. For the channel number I think it makes sense to explicitly define in the input file.

**Comment by gabrielfedel** [comment]
Ok! I will do a new version considering this.

**Comment by gabrielfedel** [comment]
Changes are done!

**Pull request merged**
